// ═════════════════════════ OFF NL BULK SEEDER ═════════════════════════
// Runs during Vercel `prebuild`. Fetches top-2000 most-scanned products in
// the Netherlands from OpenFoodFacts and bakes them into src/local_off_nl.js.
//
// If the OFF API is unreachable or returns too few items, the existing
// committed local_off_nl.js is preserved (no corruption).
//
// To force a refresh locally: `node scripts/seed-off-nl.mjs`
// To skip in CI (e.g. for fast deploys): set SKIP_OFF_SEED=1
// ═══════════════════════════════════════════════════════════════════════

import fs from 'node:fs';
import path from 'node:path';

const OUT = path.resolve('./src/local_off_nl.js');
const UA  = 'FitnessApp-Seeder/1.0 (luukbogers@outlook.com)';
const PAGES = 20;        // 20 × 100 = 2000 products max
const PAGE_SIZE = 100;
const MIN_KEEP = 100;    // Below this, keep existing file
const FIELDS = 'code,product_name,product_name_nl,brands,nutriments,image_front_small_url,quantity';

if (process.env.SKIP_OFF_SEED === '1') {
  console.log('[seed-off-nl] SKIP_OFF_SEED=1 → skipping');
  process.exit(0);
}

async function fetchPage(page) {
  const u = new URL('https://world.openfoodfacts.org/cgi/search.pl');
  u.searchParams.set('action', 'process');
  u.searchParams.set('json', '1');
  u.searchParams.set('countries_tags', 'netherlands');
  u.searchParams.set('sort_by', 'unique_scans_n');
  u.searchParams.set('page_size', String(PAGE_SIZE));
  u.searchParams.set('page', String(page));
  u.searchParams.set('fields', FIELDS);
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 25000);
  try {
    const r = await fetch(u.toString(), {
      headers: { 'User-Agent': UA, Accept: 'application/json' },
      signal: ctrl.signal,
    });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const d = await r.json();
    return d.products || [];
  } finally {
    clearTimeout(timer);
  }
}

function compact(p) {
  const n = p.nutriments || {};
  const kcal = Math.round(parseFloat(n['energy-kcal_100g']) || 0);
  if (!kcal || kcal > 900) return null;                   // skip junk
  const name = (p.product_name_nl || p.product_name || '').trim();
  if (!name || name.length < 2 || name.length > 80) return null;
  const brand = Array.isArray(p.brands)
    ? (p.brands[0] || '')
    : String(p.brands || '').split(',')[0];
  return {
    c: p.code,
    n: name,
    b: brand.trim().slice(0, 40),
    k: kcal,
    p: Math.round((parseFloat(n.proteins_100g) || 0) * 10) / 10,
    h: Math.round((parseFloat(n.carbohydrates_100g) || 0) * 10) / 10,
    f: Math.round((parseFloat(n.fat_100g) || 0) * 10) / 10,
    i: (p.image_front_small_url || '').replace('https://images.openfoodfacts.org', ''),
  };
}

async function main() {
  console.log('[seed-off-nl] Fetching top-2000 NL products from OpenFoodFacts');
  const all = [];
  let failures = 0;
  for (let i = 1; i <= PAGES; i++) {
    try {
      const items = await fetchPage(i);
      all.push(...items);
      process.stdout.write(`  page ${i}/${PAGES} → +${items.length} (total ${all.length})\n`);
    } catch (e) {
      failures++;
      console.warn(`  page ${i}/${PAGES} FAILED: ${e.message}`);
      if (failures >= 5) {
        console.warn('[seed-off-nl] Too many failures, aborting fetch');
        break;
      }
    }
    await new Promise(r => setTimeout(r, 400));            // be polite to OFF
  }

  const seen = new Set();
  const out = [];
  for (const p of all) {
    if (!p.code || seen.has(p.code)) continue;
    const c = compact(p);
    if (!c) continue;
    seen.add(p.code);
    out.push(c);
  }

  console.log(`[seed-off-nl] Compacted ${out.length} valid products`);

  if (out.length < MIN_KEEP) {
    console.warn(`[seed-off-nl] Only ${out.length} valid (< ${MIN_KEEP}). Keeping existing file.`);
    process.exit(0);
  }

  const ts = new Date().toISOString();
  const body =
    '// AUTO-GENERATED by scripts/seed-off-nl.mjs — DO NOT EDIT BY HAND\n' +
    '// Top NL products from OpenFoodFacts, sorted by unique_scans_n\n' +
    `// Generated: ${ts}\n` +
    `// Count: ${out.length}\n` +
    '// Schema: c=code, n=name, b=brand, k=kcal/100g, p=protein, h=carbs, f=fat, i=image\n' +
    '\n' +
    `export const OFF_NL_GENERATED_AT = '${ts}';\n` +
    `export const OFF_NL = ${JSON.stringify(out)};\n`;

  fs.writeFileSync(OUT, body);
  const kb = Math.round(fs.statSync(OUT).size / 1024);
  console.log(`[seed-off-nl] ✓ Wrote ${out.length} products to src/local_off_nl.js (${kb} KB)`);
}

main().catch(e => {
  console.error('[seed-off-nl] Fatal:', e.message);
  console.warn('[seed-off-nl] Keeping existing local_off_nl.js (no overwrite on failure)');
  process.exit(0);  // Don't fail the build — let existing file ship
});
