// AUTO-GENERATED by scripts/seed-off-nl.mjs — DO NOT EDIT BY HAND
// Top NL products from OpenFoodFacts, sorted by unique_scans_n
// Generated: placeholder (will be populated at next Vercel build)
// Schema: c=code, n=name, b=brand, k=kcal/100g, p=protein, h=carbs, f=fat, i=image

export const OFF_NL_GENERATED_AT = '1970-01-01T00:00:00.000Z';
export const OFF_NL = [];
